/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#0e1323",
        "surface-dim": "#0e1323",
        "surface-bright": "#34394a",
        "surface-container-lowest": "#080d1d",
        "surface-container-low": "#161b2b",
        "surface-container": "#161b2b",
        "surface-container-high": "#242f49",
        "surface-container-highest": "#34394a",
        "on-surface": "#e2e2e9",
        "on-surface-variant": "#c4c6d0",
        "inverse-surface": "#e2e2e9",
        "inverse-on-surface": "#cfd4e5",
        "outline": "#8e9099",
        "outline-variant": "#44474e",
        "surface-tint": "#ffa586",
        "primary": "#ffa586",
        "on-primary": "#ffffff",
        "primary-container": "#541a2b",
        "on-primary-container": "#ffdad6",
        "inverse-primary": "#ffa586",
        "secondary": "#ffa586",
        "on-secondary": "#ffffff",
        "secondary-container": "#541a2b",
        "on-secondary-container": "#ffdad6",
        "tertiary": "#ffa586",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b51a2b",
        "on-tertiary-container": "#e2e2e9",
        "error": "#b51a2b",
        "on-error": "#ffffff",
        "error-container": "#541a2b",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffa586",
        "primary-fixed-dim": "#ffa586",
        "on-primary-fixed": "#1a1b21",
        "on-primary-fixed-variant": "#44474e",
        "secondary-fixed": "#ffa586",
        "secondary-fixed-dim": "#ffa586",
        "on-secondary-fixed": "#1a1b21",
        "on-secondary-fixed-variant": "#44474e",
        "tertiary-fixed": "#ffa586",
        "tertiary-fixed-dim": "#ffa586",
        "on-tertiary-fixed": "#1a1b21",
        "on-tertiary-fixed-variant": "#44474e",
        "background": "#0e1323",
        "on-background": "#e2e2e9",
        "surface-variant": "#242f49",
        "dusk-violet": "#0e1323",
        "muted-rose": "#b51a2b",
        "soft-peach": "#ffa586",
        "off-white": "#f8f9ff",
        "surface-overlay": "rgba(14, 19, 35, 0.7)",
        "grid-line": "#384358",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        grid_column_gap: "16px",
        margin_edge: "24px",
        panel_padding: "20px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-base": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "data-telemetry": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "data-telemetry": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

